import type { Bank, BenchmarkGroup, BenchmarkComponent, BenchmarkCell, SourcePair, CrawlItem, IntelligenceItem, SourceAlert } from '../types/index.ts';

export const DEFAULT_ORG_ID = '00000000-0000-0000-0000-000000000001';

export const INITIAL_BANKS: Bank[] = [
  { id: 'bank-mb',      org_id: DEFAULT_ORG_ID, name: 'BIZ MBBank',            code: 'MB',      is_mb: true,  active: true, display_order: 0 },
  { id: 'bank-bidv',    org_id: DEFAULT_ORG_ID, name: 'BIDV (BIDV Direct)',     code: 'BIDV',    is_mb: false, active: true, display_order: 1 },
  { id: 'bank-vcb',     org_id: DEFAULT_ORG_ID, name: 'Vietcombank',           code: 'VCB',     is_mb: false, active: true, display_order: 2 },
  { id: 'bank-ctg',     org_id: DEFAULT_ORG_ID, name: 'VietinBank eFAST',      code: 'CTG',     is_mb: false, active: true, display_order: 3 },
  { id: 'bank-tcb',     org_id: DEFAULT_ORG_ID, name: 'Techcombank Business',   code: 'TCB',    is_mb: false, active: true, display_order: 4 },
  { id: 'bank-vpb',     org_id: DEFAULT_ORG_ID, name: 'VPBank NEOBiz',         code: 'VPB',     is_mb: false, active: true, display_order: 5 },
  { id: 'bank-acb',     org_id: DEFAULT_ORG_ID, name: 'ACB ONE BIZ',           code: 'ACB',     is_mb: false, active: true, display_order: 6 },
  { id: 'bank-stb',     org_id: DEFAULT_ORG_ID, name: 'Sacombank',             code: 'STB',     is_mb: false, active: true, display_order: 7 },
  { id: 'bank-shb',     org_id: DEFAULT_ORG_ID, name: 'SHB Corporate',         code: 'SHB',     is_mb: false, active: true, display_order: 8 },
  { id: 'bank-hdb',     org_id: DEFAULT_ORG_ID, name: 'HDBank',                code: 'HDB',     is_mb: false, active: true, display_order: 9 },
  { id: 'bank-tpb',     org_id: DEFAULT_ORG_ID, name: 'TPBank Biz',            code: 'TPB',     is_mb: false, active: true, display_order: 10 },
  { id: 'bank-vib',     org_id: DEFAULT_ORG_ID, name: 'VIB',                   code: 'VIB',     is_mb: false, active: true, display_order: 11 },
  { id: 'bank-msb',     org_id: DEFAULT_ORG_ID, name: 'MSB',                   code: 'MSB',     is_mb: false, active: true, display_order: 12 },
  { id: 'bank-ocb',     org_id: DEFAULT_ORG_ID, name: 'OCB OMNI Corp',         code: 'OCB',     is_mb: false, active: true, display_order: 13 },
  { id: 'bank-ssb',     org_id: DEFAULT_ORG_ID, name: 'SeABank',               code: 'SSB',     is_mb: false, active: true, display_order: 14 },
  { id: 'bank-agr',     org_id: DEFAULT_ORG_ID, name: 'Agribank',              code: 'AGR',     is_mb: false, active: true, display_order: 15 },
];

export const INITIAL_SOURCE_PAIRS: SourcePair[] = [
  // 1. MB Bank — Doanh nghiệp
  {
    id: 'pair-1',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-mb',
    bank_name: 'MB Bank',
    facebook_url: 'https://www.facebook.com/VietnamMBBank',
    website_url: 'https://www.mbbank.com.vn/khach-hang-doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 0,
  },
  // 2. BIDV — Doanh nghiệp
  {
    id: 'pair-2',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-bidv',
    bank_name: 'BIDV',
    facebook_url: 'https://www.facebook.com/BIDVbankvietnam',
    website_url: 'https://www.bidv.com.vn/vi/khach-hang-doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 1,
  },
  // 3. Vietcombank — Doanh nghiệp
  {
    id: 'pair-3',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-vcb',
    bank_name: 'Vietcombank',
    facebook_url: 'https://www.facebook.com/vietcombank',
    website_url: 'https://www.vietcombank.com.vn/khach-hang-doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 2,
  },
  // 4. VietinBank — Doanh nghiệp (eFAST)
  {
    id: 'pair-4',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-ctg',
    bank_name: 'VietinBank',
    facebook_url: 'https://www.facebook.com/VietinBank',
    website_url: 'https://vietinbank.vn/vi/khach-hang-doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 3,
  },
  // 5. Techcombank — Doanh nghiệp
  {
    id: 'pair-5',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-tcb',
    bank_name: 'Techcombank',
    facebook_url: 'https://www.facebook.com/Techcombank',
    website_url: 'https://techcombank.com/khach-hang-doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 4,
  },
  // 6. VPBank — Doanh nghiệp (NEOBiz)
  {
    id: 'pair-6',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-vpb',
    bank_name: 'VPBank',
    facebook_url: 'https://www.facebook.com/VPBankOfficial',
    website_url: 'https://www.vpbank.com.vn/doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 5,
  },
  // 7. ACB — Doanh nghiệp
  {
    id: 'pair-7',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-acb',
    bank_name: 'ACB',
    facebook_url: 'https://www.facebook.com/NganHangACB',
    website_url: 'https://www.acb.com.vn/san-pham-dich-vu/khach-hang-doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 6,
  },
  // 8. Sacombank — Doanh nghiệp
  {
    id: 'pair-8',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-stb',
    bank_name: 'Sacombank',
    facebook_url: 'https://www.facebook.com/SacombankOfficial',
    website_url: 'https://www.sacombank.com.vn/doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 7,
  },
  // 9. SHB — Doanh nghiệp
  {
    id: 'pair-9',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-shb',
    bank_name: 'SHB',
    facebook_url: 'https://www.facebook.com/SHBOfficial',
    website_url: 'https://www.shb.com.vn/khach-hang-doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 8,
  },
  // 10. HDBank — Doanh nghiệp
  {
    id: 'pair-10',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-hdb',
    bank_name: 'HDBank',
    facebook_url: 'https://www.facebook.com/HDBankFanpage',
    website_url: 'https://hdbank.com.vn/vi/corporate',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 9,
  },
  // 11. TPBank — Doanh nghiệp
  {
    id: 'pair-11',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-tpb',
    bank_name: 'TPBank',
    facebook_url: 'https://www.facebook.com/TPBank',
    website_url: 'https://tpb.vn/doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 10,
  },
  // 12. VIB — Doanh nghiệp
  {
    id: 'pair-12',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-vib',
    bank_name: 'VIB',
    facebook_url: 'https://www.facebook.com/VIB.NganHangQuocTe',
    website_url: 'https://www.vib.com.vn/vn/doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 11,
  },
  // 13. MSB — Doanh nghiệp
  {
    id: 'pair-13',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-msb',
    bank_name: 'MSB',
    facebook_url: 'https://www.facebook.com/MSB.NganHangHangHai',
    website_url: 'https://www.msb.com.vn/vi/doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 12,
  },
  // 14. OCB — Doanh nghiệp
  {
    id: 'pair-14',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-ocb',
    bank_name: 'OCB',
    facebook_url: 'https://www.facebook.com/phuongdongbank',
    website_url: 'https://ocb.com.vn/vi/doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 13,
  },
  // 15. SeABank — Doanh nghiệp
  {
    id: 'pair-15',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-ssb',
    bank_name: 'SeABank',
    facebook_url: 'https://www.facebook.com/NganhangSeABank',
    website_url: 'https://www.seabank.com.vn/doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 14,
  },
  // 16. Agribank — Doanh nghiệp
  {
    id: 'pair-16',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-agr',
    bank_name: 'Agribank',
    facebook_url: 'https://www.facebook.com/agribankvietnam',
    website_url: 'https://www.agribank.com.vn/vn/khach-hang-doanh-nghiep',
    facebook_verified: true,
    website_verified: true,
    is_active: true,
    display_order: 15,
  },
];


export const INITIAL_CRAWL_ITEMS: CrawlItem[] = [
  {
    id: 'item-1',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-tcb',
    bank_name: 'Techcombank',
    source_type: 'facebook',
    source_url: 'https://www.facebook.com/techcombank',
    detected_at: '2024-03-12',
    title: 'Ra mắt tính năng thanh toán...',
    feature_name: 'Apple Pay trên Techcombank',
    content_hash: 'hash-tcb-1',
    status: 'new',
  },
  {
    id: 'item-2',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-ctg',
    bank_name: 'VietinBank',
    source_type: 'facebook',
    source_url: 'https://www.facebook.com/vietinbank',
    detected_at: '2024-03-10',
    title: 'Ưu đãi phí chuyển tiền quốc tế',
    feature_name: 'Chuyển tiền quốc tế',
    content_hash: 'hash-ctg-1',
    status: 'new',
  },
  {
    id: 'item-3',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-vpb',
    bank_name: 'VPBank',
    source_type: 'website',
    source_url: 'https://www.vpbank.com.vn',
    detected_at: '2024-03-08',
    title: 'Giải pháp tài trợ chuỗi cung ứng',
    feature_name: 'Cấp hạn mức tín dụng',
    content_hash: 'hash-vpb-1',
    status: 'new',
  },
  {
    id: 'item-4',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-bidv',
    bank_name: 'BIDV',
    source_type: 'website',
    source_url: 'https://www.bidv.com.vn',
    detected_at: '2024-03-05',
    title: 'Dịch vụ nộp thuế doanh nghiệp',
    feature_name: 'Nộp thuế / hóa đơn',
    content_hash: 'hash-bidv-1',
    status: 'new',
  },
  {
    id: 'item-5',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-vcb',
    bank_name: 'Vietcombank',
    source_type: 'facebook',
    source_url: 'https://www.facebook.com/vietcombank',
    detected_at: '2024-03-03',
    title: 'SME Grow - Đồng hành cùng doanh nghiệp',
    feature_name: 'SME Grow',
    content_hash: 'hash-vcb-1',
    status: 'new',
  },
  {
    id: 'item-6',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-tcb',
    bank_name: 'Techcombank',
    source_type: 'website',
    source_url: 'https://www.techcombank.com.vn',
    detected_at: '2024-03-01',
    title: 'Cập nhật chuyển tiền định kỳ',
    feature_name: 'Scheduled Transfer',
    content_hash: 'hash-tcb-2',
    status: 'new',
  },
  {
    id: 'item-7',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-vpb',
    bank_name: 'VPBank',
    source_type: 'facebook',
    source_url: 'https://www.facebook.com/vpbank',
    detected_at: '2024-02-26',
    title: 'NEOBiz cập nhật trải nghiệm',
    feature_name: 'Dashboard doanh nghiệp',
    content_hash: 'hash-vpb-2',
    status: 'new',
  },
  {
    id: 'item-8',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-bidv',
    bank_name: 'BIDV',
    source_type: 'website',
    source_url: 'https://www.bidv.com.vn',
    detected_at: '2024-02-22',
    title: 'Nâng cấp sao kê tài khoản',
    feature_name: 'Đối chiếu tài khoản',
    content_hash: 'hash-bidv-2',
    status: 'new',
  },
  {
    id: 'item-9',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-ctg',
    bank_name: 'VietinBank',
    source_type: 'website',
    source_url: 'https://www.vietinbank.vn',
    detected_at: '2024-02-20',
    title: 'eFAST nâng cấp giải ngân',
    feature_name: 'Giải ngân số',
    content_hash: 'hash-ctg-2',
    status: 'new',
  },
  {
    id: 'item-10',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-tcb',
    bank_name: 'Techcombank',
    source_type: 'facebook',
    source_url: 'https://www.facebook.com/techcombank',
    detected_at: '2024-02-18',
    title: 'Tính năng quản trị thẻ',
    feature_name: 'Card Management',
    content_hash: 'hash-tcb-3',
    status: 'new',
  },
  {
    id: 'item-11',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-bidv',
    bank_name: 'BIDV',
    source_type: 'facebook',
    source_url: 'https://www.facebook.com/bidv',
    detected_at: '2024-02-14',
    title: 'Ra mắt sản phẩm tiền gửi số',
    feature_name: 'Tiền gửi trực tuyến',
    content_hash: 'hash-bidv-3',
    status: 'new',
  },
  {
    id: 'item-12',
    org_id: DEFAULT_ORG_ID,
    bank_id: 'bank-vpb',
    bank_name: 'VPBank',
    source_type: 'website',
    source_url: 'https://www.vpbank.com.vn',
    detected_at: '2024-02-10',
    title: 'Cải tiến bảo lãnh điện tử',
    feature_name: 'eGuarantee',
    content_hash: 'hash-vpb-3',
    status: 'new',
  },
];

export const INITIAL_GROUPS: BenchmarkGroup[] = [
  { id: 'group-a', org_id: DEFAULT_ORG_ID, name: 'A. ONBOARDING', display_order: 0, active: true, side: 'left' },
  { id: 'group-b', org_id: DEFAULT_ORG_ID, name: 'B. TÀI KHOẢN & THANH TOÁN', display_order: 1, active: true, side: 'left' },
  { id: 'group-c1', org_id: DEFAULT_ORG_ID, name: 'C. TIỀN GỬI VÀ ĐẦU TƯ', display_order: 2, active: true, side: 'left' },
  { id: 'group-c2', org_id: DEFAULT_ORG_ID, name: 'C. TÀI TRỢ THƯƠNG MẠI', display_order: 3, active: true, side: 'right' },
  { id: 'group-d', org_id: DEFAULT_ORG_ID, name: 'D. TÍN DỤNG', display_order: 4, active: true, side: 'right' },
  { id: 'group-e', org_id: DEFAULT_ORG_ID, name: 'E. QUẢN TRỊ TÀI CHÍNH', display_order: 5, active: true, side: 'right' },
];

export const INITIAL_COMPONENTS: BenchmarkComponent[] = [
  // A. ONBOARDING
  { id: 'comp-1', org_id: DEFAULT_ORG_ID, group_id: 'group-a', name: 'Mở TK online', display_order: 0, active: true },
  // B. TÀI KHOẢN & THANH TOÁN
  { id: 'comp-2', org_id: DEFAULT_ORG_ID, group_id: 'group-b', name: 'Homepage', display_order: 1, active: true },
  { id: 'comp-3', org_id: DEFAULT_ORG_ID, group_id: 'group-b', name: 'Sao kê/sổ phụ', display_order: 2, active: true },
  { id: 'comp-4', org_id: DEFAULT_ORG_ID, group_id: 'group-b', name: 'Chuyển tiền 24/7 & theo lô', display_order: 3, active: true },
  { id: 'comp-5', org_id: DEFAULT_ORG_ID, group_id: 'group-b', name: 'Nộp thuế / hải quan / hóa đơn', display_order: 4, active: true },
  { id: 'comp-6', org_id: DEFAULT_ORG_ID, group_id: 'group-b', name: 'Thẻ doanh nghiệp online', display_order: 5, active: true },
  { id: 'comp-7', org_id: DEFAULT_ORG_ID, group_id: 'group-b', name: 'Thanh toán quốc tế online', display_order: 6, active: true },
  // C. TIỀN GỬI VÀ ĐẦU TƯ
  { id: 'comp-8', org_id: DEFAULT_ORG_ID, group_id: 'group-c1', name: 'Tiền gửi CKH online', display_order: 7, active: true },
  { id: 'comp-9', org_id: DEFAULT_ORG_ID, group_id: 'group-c1', name: 'Sinh lời tự động', display_order: 8, active: true },
  { id: 'comp-10', org_id: DEFAULT_ORG_ID, group_id: 'group-c1', name: 'CDs', display_order: 9, active: true },
  { id: 'comp-11', org_id: DEFAULT_ORG_ID, group_id: 'group-c1', name: 'Sản phẩm đầu tư khác', display_order: 10, active: true },
  // C. TÀI TRỢ THƯƠNG MẠI
  { id: 'comp-12', org_id: DEFAULT_ORG_ID, group_id: 'group-c2', name: 'Mua bán ngoại tệ online', display_order: 11, active: true },
  { id: 'comp-13', org_id: DEFAULT_ORG_ID, group_id: 'group-c2', name: 'L/C online', display_order: 12, active: true },
  // D. TÍN DỤNG
  { id: 'comp-14', org_id: DEFAULT_ORG_ID, group_id: 'group-d', name: 'Cấp hạn mức', display_order: 13, active: true },
  { id: 'comp-15', org_id: DEFAULT_ORG_ID, group_id: 'group-d', name: 'Ký kết văn kiện tín dụng', display_order: 14, active: true },
  { id: 'comp-16', org_id: DEFAULT_ORG_ID, group_id: 'group-d', name: 'Giải ngân online', display_order: 15, active: true },
  { id: 'comp-17', org_id: DEFAULT_ORG_ID, group_id: 'group-d', name: 'Bảo lãnh online', display_order: 16, active: true },
  // E. QUẢN TRỊ TÀI CHÍNH
  { id: 'comp-18', org_id: DEFAULT_ORG_ID, group_id: 'group-e', name: '360 Độ doanh nghiệp', display_order: 17, active: true },
  { id: 'comp-19', org_id: DEFAULT_ORG_ID, group_id: 'group-e', name: 'SME Grow', display_order: 18, active: true },
];

export const INITIAL_CELLS: BenchmarkCell[] = [
  // 1. Mở TK online
  { id: 'c-1-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-1', bank_id: 'bank-mb', score: 3, description: 'Có — ~3 phút, chọn TK số đẹp\nMở tài khoản xong có thể giao dịch được ngay.\nHồ sơ mở tài khoản thiếu có thể bổ sung online' },
  { id: 'c-1-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-1', bank_id: 'bank-tcb', score: 1, description: 'Có — ~10 phút, chọn số TK đẹp.\nMở tài khoản online cần xác minh tại quầy trước khi giao dịch\nHồ sơ thiếu cần bổ sung tại quầy' },
  { id: 'c-1-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-1', bank_id: 'bank-ctg', score: 1, description: 'Có.\nMở tài khoản online cần xác minh tại quầy trước khi giao dịch\nHồ sơ thiếu cần bổ sung tại quầy' },
  { id: 'c-1-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-1', bank_id: 'bank-bidv', score: 1, description: 'Có\nMở tài khoản online cần xác minh tại quầy trước khi giao dịch\nHồ sơ thiếu cần bổ sung tại quầy' },
  { id: 'c-1-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-1', bank_id: 'bank-vpb', score: 1, description: 'Có - ~5 phút\nMở tài khoản online cần xác minh tại quầy trước khi giao dịch\nHồ sơ thiếu cần bổ sung tại quầy' },

  // 2. Homepage
  { id: 'c-2-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-2', bank_id: 'bank-mb', score: 2, description: 'Có — có số dư (bao gồm VNĐ + ngoại tệ)\nCó dòng tiền\nCó danh sách giao dịch gần đây của Maker và Checker' },
  { id: 'c-2-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-2', bank_id: 'bank-tcb', score: 2, description: 'Có — dashboard có:\n- số dư (bao gồm VNĐ + ngoại tệ)\n- Tổng tiền gửi\n- Tổng khoản vay\n- có dòng tiền' },
  { id: 'c-2-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-2', bank_id: 'bank-ctg', score: 2, description: 'Có số dư, biểu đồ thu-chi theo tháng\nnhư các ví điện tử' },
  { id: 'c-2-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-2', bank_id: 'bank-bidv', score: 2, description: 'Có — dashboard có:\n- số dư (bao gồm VNĐ + ngoại tệ)\n- Tổng tiền gửi\n- Tổng khoản vay\n- Dòng tiền vào - ra, SK giao dịch' },
  { id: 'c-2-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-2', bank_id: 'bank-vpb', score: 2, description: 'Có số dư, tiền gửi, khoản vay, sao kê GD gần nhất\nChưa có biểu đồ thu chi, dòng tiền' },

  // 3. Sao kê/sổ phụ
  { id: 'c-3-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-3', bank_id: 'bank-mb', score: 2, description: 'Có' },
  { id: 'c-3-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-3', bank_id: 'bank-tcb', score: 2, description: 'Có' },
  { id: 'c-3-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-3', bank_id: 'bank-ctg', score: 2, description: 'Có' },
  { id: 'c-3-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-3', bank_id: 'bank-bidv', score: 3, description: 'Có, thêm các tính năng\n- Sao kê/sổ phụ\n- Xác nhận số dư từ ngân hàng\n- Đối chiếu tài khoản' },
  { id: 'c-3-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-3', bank_id: 'bank-vpb', score: 2, description: 'Có' },

  // 4. Chuyển tiền 24/7 & theo lô
  { id: 'c-4-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-4', bank_id: 'bank-mb', score: 2, description: 'Có — chuyển tiền nhanh 24/7, theo lô, mã citad\nChuyển ngoại tệ trong nước\nChuyển lương VND\nChưa có chuyển lương ngoại tệ\nChưa có đặt lệnh giao dịch trong tương lai\nChưa có tra soát online' },
  { id: 'c-4-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-4', bank_id: 'bank-tcb', score: 3, description: 'Có — chuyển tiền nhanh 24/7 và theo lô,\ncó tính năng đặt lịch chuyển tiền, có tính năng yêu cầu tra soát chuyển tiền,\ncó đặt lệnh giao dịch trong tương lai' },
  { id: 'c-4-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-4', bank_id: 'bank-ctg', score: 2, description: 'Có — qua TK 24/7 (new), tối đa 5000 GD/file, số tiền tối đa 1 GD đi ngoài hệ thống trên file 500trđ' },
  { id: 'c-4-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-4', bank_id: 'bank-bidv', score: 3, description: 'Có — chuyển tiền nhanh 24/7 và theo lô,\ncó tính năng đặt lịch chuyển tiền, có tính năng yêu cầu tra soát chuyển tiền,\ncó đặt lệnh giao dịch trong tương lai' },
  { id: 'c-4-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-4', bank_id: 'bank-vpb', score: 3, description: 'Có chuyển tiền 24/7/lương/lô (giới hạn 10,000 giao dịch/file chuyển tiền theo lô)\nCó tính năng chuyển tiền định kỳ' },

  // 5. Nộp thuế / hải quan / hóa đơn
  { id: 'c-5-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-5', bank_id: 'bank-mb', score: 2, description: 'Có' },
  { id: 'c-5-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-5', bank_id: 'bank-tcb', score: 2, description: 'Có' },
  { id: 'c-5-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-5', bank_id: 'bank-ctg', score: 2, description: 'Có' },
  { id: 'c-5-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-5', bank_id: 'bank-bidv', score: 2, description: 'Có' },
  { id: 'c-5-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-5', bank_id: 'bank-vpb', score: 2, description: 'Có' },

  // 6. Thẻ doanh nghiệp online
  { id: 'c-6-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-6', bank_id: 'bank-mb', score: 2, description: 'Có phát hành thẻ\nCó quản trị thẻ online\nChưa có thanh toán thẻ' },
  { id: 'c-6-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-6', bank_id: 'bank-tcb', score: 3, description: 'Có phát hành thẻ\nCó quản trị thẻ online\nCó thanh toán thẻ' },
  { id: 'c-6-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-6', bank_id: 'bank-ctg', score: 1, description: 'Chưa có phát hành thẻ\nCó quản trị thẻ online' },
  { id: 'c-6-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-6', bank_id: 'bank-bidv', score: 1, description: 'Chưa có phát hành thẻ\nCó quản trị thẻ online\nCó thanh toán thẻ' },
  { id: 'c-6-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-6', bank_id: 'bank-vpb', score: 0, description: 'Không có' },

  // 7. Thanh toán quốc tế online
  { id: 'c-7-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-7', bank_id: 'bank-mb', score: 2, description: 'Có — chuyển tiền quốc tế online, truy vấn, tra soát, bổ sung chứng từ online\nChưa cho phép thanh toán nhiều đối tác cùng lúc' },
  { id: 'c-7-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-7', bank_id: 'bank-tcb', score: 3, description: 'Có — CTQT online, không giới hạn COT\nCho phép CTQT nhiều đối tác cùng lúc\nBổ sung chứng từ không qua cấp duyệt' },
  { id: 'c-7-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-7', bank_id: 'bank-ctg', score: 2, description: 'Có — chuyển tiền quốc tế online, truy vấn, tra soát, bổ sung chứng từ online\nChưa cho phép thanh toán nhiều đối tác cùng lúc' },
  { id: 'c-7-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-7', bank_id: 'bank-bidv', score: 3, description: 'Chuyển tiền quốc tế online, truy vấn, tra soát\nBổ sung chứng từ online\nCho phép CTQT nhiều đối tác cùng lúc' },
  { id: 'c-7-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-7', bank_id: 'bank-vpb', score: 2, description: 'Chuyển tiền quốc tế online, truy vấn, tra soát, bổ sung chứng từ online' },

  // 8. Tiền gửi CKH online
  { id: 'c-8-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-8', bank_id: 'bank-mb', score: 2, description: 'Có' },
  { id: 'c-8-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-8', bank_id: 'bank-tcb', score: 2, description: 'Có' },
  { id: 'c-8-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-8', bank_id: 'bank-ctg', score: 2, description: 'Có' },
  { id: 'c-8-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-8', bank_id: 'bank-bidv', score: 2, description: 'Có' },
  { id: 'c-8-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-8', bank_id: 'bank-vpb', score: 2, description: 'Có' },

  // 9. Sinh lời tự động
  { id: 'c-9-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-9', bank_id: 'bank-mb', score: 0, description: 'Chưa có' },
  { id: 'c-9-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-9', bank_id: 'bank-tcb', score: 3, description: 'Có' },
  { id: 'c-9-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-9', bank_id: 'bank-ctg', score: 0, description: 'Chưa có' },
  { id: 'c-9-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-9', bank_id: 'bank-bidv', score: 3, description: 'Có' },
  { id: 'c-9-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-9', bank_id: 'bank-vpb', score: 0, description: 'Chưa có' },

  // 10. CDs
  { id: 'c-10-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-10', bank_id: 'bank-mb', score: 2, description: 'Có' },
  { id: 'c-10-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-10', bank_id: 'bank-tcb', score: 2, description: 'Có' },
  { id: 'c-10-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-10', bank_id: 'bank-ctg', score: 0, description: 'Chưa có' },
  { id: 'c-10-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-10', bank_id: 'bank-bidv', score: 2, description: 'Có' },
  { id: 'c-10-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-10', bank_id: 'bank-vpb', score: 0, description: 'Chưa có' },

  // 11. Sản phẩm đầu tư khác
  { id: 'c-11-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-11', bank_id: 'bank-mb', score: 0, description: 'Chưa có' },
  { id: 'c-11-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-11', bank_id: 'bank-tcb', score: 2, description: 'Có' },
  { id: 'c-11-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-11', bank_id: 'bank-ctg', score: 0, description: 'Chưa có' },
  { id: 'c-11-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-11', bank_id: 'bank-bidv', score: 0, description: 'Chưa có' },
  { id: 'c-11-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-11', bank_id: 'bank-vpb', score: 0, description: 'Chưa có' },

  // 12. Mua bán ngoại tệ online
  { id: 'c-12-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-12', bank_id: 'bank-mb', score: 3, description: 'Có khóa tỷ giá cố định\nCó mbeechat tỷ giá ngay trên BIZ' },
  { id: 'c-12-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-12', bank_id: 'bank-tcb', score: 2, description: 'Có khóa tỷ giá cố định\nKhông có mbeechat realtime' },
  { id: 'c-12-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-12', bank_id: 'bank-ctg', score: 3, description: 'Có module bảng giá giao dịch để KH theo dõi biến động tỷ giá\nKhông có mbeechat realtime' },
  { id: 'c-12-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-12', bank_id: 'bank-bidv', score: 2, description: 'Có khóa tỷ giá cố định\nKhông có mbeechat realtime' },
  { id: 'c-12-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-12', bank_id: 'bank-vpb', score: 2, description: 'Có khóa tỷ giá cố định\nKhông có mbeechat realtime' },

  // 13. L/C online
  { id: 'c-13-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-13', bank_id: 'bank-mb', score: 3, description: 'Có tư vấn, phát hành, thanh toán LC online' },
  { id: 'c-13-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-13', bank_id: 'bank-tcb', score: 1, description: 'Có phát hành LC trong khoảng 1 giờ, chưa có tư vấn, thanh toán LC' },
  { id: 'c-13-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-13', bank_id: 'bank-ctg', score: 1, description: 'Có phát hành LC theo hạn mức, chưa có tư vấn và thanh toán LC' },
  { id: 'c-13-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-13', bank_id: 'bank-bidv', score: 1, description: 'Có phát hành LC theo hạn mức, chưa có tư vấn và thanh toán LC' },
  { id: 'c-13-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-13', bank_id: 'bank-vpb', score: 1, description: 'Có phát hành LC theo hạn mức, chưa có tư vấn và thanh toán LC' },

  // 14. Cấp hạn mức
  { id: 'c-14-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-14', bank_id: 'bank-mb', score: 3, description: '1. Có đề nghị cấp hạn mức/điều chỉnh hạn mức online.\n2. Có cấp tín dụng theo quy trình preapproved trọn luồng kênh số.\n3. Có luồng ngân hàng chủ động tái cấp khi đến hạn hạn mức' },
  { id: 'c-14-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-14', bank_id: 'bank-tcb', score: 2, description: '1. Có đề nghị cấp hạn mức online\n2. Có hạn mức pre-approved tới 20 tỷ\n3. Chưa có luồng ngân hàng chủ động tái cấp khi đến hạn hạn mức' },
  { id: 'c-14-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-14', bank_id: 'bank-ctg', score: 2, description: '1. Có cấp hạn mức online\n2. Không có luồng pre tín chấp online\n3. Chưa có luồng ngân hàng chủ động tái cấp khi đến hạn hạn mức' },
  { id: 'c-14-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-14', bank_id: 'bank-bidv', score: 0, description: '1. Không có cấp hạn mức online\n2. Không có luồng Preapproved online\n3. Chưa có luồng ngân hàng chủ động tái cấp khi đến hạn hạn mức' },
  { id: 'c-14-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-14', bank_id: 'bank-vpb', score: 2, description: '1. Có cấp hạn mức online\n2. Không có luồng pre tín chấp online\n3. Chưa có luồng ngân hàng chủ động tái cấp khi đến hạn hạn mức' },

  // 15. Ký kết văn kiện tín dụng
  { id: 'c-15-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-15', bank_id: 'bank-mb', score: 3, description: 'Có ký số các loại văn kiện tín dụng với doanh nghiệp (trừ văn kiện thế chấp cần công chứng) với tất cả các phương án' },
  { id: 'c-15-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-15', bank_id: 'bank-tcb', score: 0, description: 'Chưa có' },
  { id: 'c-15-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-15', bank_id: 'bank-ctg', score: 0, description: 'Chưa có' },
  { id: 'c-15-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-15', bank_id: 'bank-bidv', score: 0, description: 'Chưa có' },
  { id: 'c-15-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-15', bank_id: 'bank-vpb', score: 1, description: 'Có ký số văn kiện tín dụng doanh nghiệp tuy nhiên chỉ ký được với HĐTD của sản phẩm thấu chi tín chấp' },

  // 16. Giải ngân online
  { id: 'c-16-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-16', bank_id: 'bank-mb', score: 3, description: '1. Có giải ngân online\n2. Có giải ngân tự động, khách hàng nhận tiền ngay sau khi khách hàng duyệt trên nền tảng ebanking.' },
  { id: 'c-16-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-16', bank_id: 'bank-tcb', score: 3, description: '1. Có giải ngân online\n2. Có giải ngân tự động, khách hàng nhận tiền ngay sau khi khách hàng duyệt trên nền tảng ebanking.' },
  { id: 'c-16-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-16', bank_id: 'bank-ctg', score: 2, description: '1. Có giải ngân online\n2. Không có giải ngân tự động' },
  { id: 'c-16-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-16', bank_id: 'bank-bidv', score: 2, description: '1. Có giải ngân online\n2. Không có giải ngân tự động' },
  { id: 'c-16-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-16', bank_id: 'bank-vpb', score: 3, description: '1. Có giải ngân online\n2. Có giải ngân tự động, khách hàng nhận tiền ngay sau khi khách hàng duyệt trên nền tảng ebanking.' },

  // 17. Bảo lãnh online
  { id: 'c-17-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-17', bank_id: 'bank-mb', score: 2, description: '1. Có bảo lãnh online\n2. Có bảo lãnh tích hợp eGP' },
  { id: 'c-17-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-17', bank_id: 'bank-tcb', score: 2, description: 'Có phát hành bảo lãnh online trong 1–2 giờ\nCó bảo lãnh tích hợp eGP' },
  { id: 'c-17-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-17', bank_id: 'bank-ctg', score: 2, description: 'Có bảo lãnh online\nCó bảo lãnh tích hợp eGP' },
  { id: 'c-17-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-17', bank_id: 'bank-bidv', score: 2, description: 'Có bảo lãnh online\nCó bảo lãnh tích hợp eGP' },
  { id: 'c-17-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-17', bank_id: 'bank-vpb', score: 2, description: 'Có bảo lãnh online\nCó bảo lãnh tích hợp eGP' },

  // 18. 360 Độ doanh nghiệp
  { id: 'c-18-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-18', bank_id: 'bank-mb', score: 2, description: 'Giai đoạn 1: Xem thông tin doanh nghiệp: thông tin chung, danh sách người dùng BIZ, thay đổi hạn mức giao dịch\nGiai đoạn 2 (dự kiến): Upload, lưu trữ hồ sơ tài chính/pháp lý, thay đổi thông tin DN, quản trị khóa/mở user BIZ' },
  { id: 'c-18-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-18', bank_id: 'bank-tcb', score: 2, description: 'Xem thông tin doanh nghiệp: thông tin chung, danh sách người dùng BIZ, thay đổi hạn mức giao dịch' },
  { id: 'c-18-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-18', bank_id: 'bank-ctg', score: 0, description: 'Chưa có' },
  { id: 'c-18-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-18', bank_id: 'bank-bidv', score: 2, description: 'Xem thông tin doanh nghiệp: thông tin chung, danh sách người dùng BIZ, thay đổi hạn mức giao dịch' },
  { id: 'c-18-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-18', bank_id: 'bank-vpb', score: 0, description: 'Chưa có' },

  // 19. SME Grow
  { id: 'c-19-mb', org_id: DEFAULT_ORG_ID, component_id: 'comp-19', bank_id: 'bank-mb', score: 3, description: 'SME Grow & phân tích thị trường\nHealth check BCTC' },
  { id: 'c-19-tcb', org_id: DEFAULT_ORG_ID, component_id: 'comp-19', bank_id: 'bank-tcb', score: 0, description: 'Chưa có' },
  { id: 'c-19-ctg', org_id: DEFAULT_ORG_ID, component_id: 'comp-19', bank_id: 'bank-ctg', score: 0, description: 'Chưa có' },
  { id: 'c-19-bidv', org_id: DEFAULT_ORG_ID, component_id: 'comp-19', bank_id: 'bank-bidv', score: 0, description: 'Chưa có' },
  { id: 'c-19-vpb', org_id: DEFAULT_ORG_ID, component_id: 'comp-19', bank_id: 'bank-vpb', score: 0, description: 'Chưa có' },
];

/* ─────────────────────────── Banking Intelligence Seeds (Top 16 Banks) ─────────────────────────── */

export const INITIAL_INTELLIGENCE_ITEMS: IntelligenceItem[] = [
  // 1. MB Bank
  {
    id: 'intel-mb-1',
    bankId: 'bank-mb',
    bankName: 'MB Bank',
    publishedAt: '2026-02-18',
    title: 'BIZ MBBank ra mắt Mở L/C trực tuyến và Bảo lãnh điện tử eGP',
    category: 'LC và bảo lãnh',
    summary: 'Doanh nghiệp SME và xuất nhập khẩu có thể phát hành thư tín dụng L/C và thư bảo lãnh dự thầu tích hợp trực tiếp Hệ thống Đấu thầu Quốc gia (e-GP) trong 2 giờ.',
    audience: 'SME & Doanh nghiệp xuất nhập khẩu',
    websiteUrl: 'https://business.mbbank.com.vn/lc-online',
    facebookUrl: 'https://www.facebook.com/VietnamMBBank/posts/1058291823901',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.98,
    collectedAt: '2026-02-19T08:30:00Z',
    isDemo: false,
  },
  {
    id: 'intel-mb-2',
    bankId: 'bank-mb',
    bankName: 'MB Bank',
    publishedAt: '2026-01-20',
    title: 'Gói ưu đãi phí chuyển tiền quốc tế 0 đồng và BIZ FX khóa tỷ giá',
    category: 'Tài trợ thương mại',
    summary: 'Chương trình miễn 100% điện phí chuyển tiền ngoại tệ và tính năng khóa tỷ giá cố định kỳ hạn trên ứng dụng BIZ MBBank.',
    audience: 'Doanh nghiệp FDI & Xuất nhập khẩu',
    websiteUrl: 'https://business.mbbank.com.vn/uu-dai-ty-gia-fx',
    facebookUrl: 'https://www.facebook.com/VietnamMBBank/posts/1059281729102',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.96,
    collectedAt: '2026-01-21T09:15:00Z',
    isDemo: false,
  },

  // 2. Techcombank
  {
    id: 'intel-tcb-1',
    bankId: 'bank-tcb',
    bankName: 'Techcombank',
    publishedAt: '2026-03-01',
    title: 'Techcombank Business nâng cấp đặt lịch chuyển tiền định kỳ & theo lô 20 tỷ',
    category: 'Thanh toán',
    summary: 'Nâng hạn mức chuyển tiền theo lô lên 20 tỷ đồng/giao dịch, bổ sung tính năng lên lịch định kỳ thanh toán lương và nhà cung cấp tự động.',
    audience: 'SME',
    websiteUrl: 'https://techcombank.com/khach-hang-doanh-nghiep/chuyen-tien-dinh-ky',
    facebookUrl: 'https://www.facebook.com/Techcombank/posts/120938472910',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.99,
    collectedAt: '2026-03-02T10:00:00Z',
    isDemo: false,
  },
  {
    id: 'intel-tcb-2',
    bankId: 'bank-tcb',
    bankName: 'Techcombank',
    publishedAt: '2026-02-10',
    title: 'Phát hành bảo lãnh điện tử e-Guarantee siêu tốc 2 giờ',
    category: 'LC và bảo lãnh',
    summary: 'Doanh nghiệp xây lắp và tổng thầu nhận thư bảo lãnh online qua Techcombank Business kết nối cổng thông tin đấu thầu trong 2 giờ làm việc.',
    audience: 'Nhà thầu & Doanh nghiệp xây dựng',
    websiteUrl: 'https://techcombank.com/khach-hang-doanh-nghiep/bao-lanh-dien-tu',
    facebookUrl: 'https://www.facebook.com/Techcombank/posts/120938472911',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.97,
    collectedAt: '2026-02-11T14:20:00Z',
    isDemo: false,
  },

  // 3. VietinBank
  {
    id: 'intel-ctg-1',
    bankId: 'bank-ctg',
    bankName: 'VietinBank',
    publishedAt: '2026-02-25',
    title: 'VietinBank eFAST số hóa trọn gói ký số văn kiện tín dụng & giải ngân online',
    category: 'Tín dụng và khoản vay',
    summary: 'Doanh nghiệp ký số các chứng thư bảo mật văn kiện tín dụng và nhận vốn giải ngân tự động 24/7 trực tiếp trên nền tảng eFAST.',
    audience: 'Khách hàng tổ chức & SME',
    websiteUrl: 'https://www.vietinbank.vn/web/home/vn/product/corporate/efast-ky-so-online.html',
    facebookUrl: 'https://www.facebook.com/VietinBank/posts/98172635190',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.98,
    collectedAt: '2026-02-26T11:00:00Z',
    isDemo: false,
  },
  {
    id: 'intel-ctg-2',
    bankId: 'bank-ctg',
    bankName: 'VietinBank',
    publishedAt: '2026-01-15',
    title: 'Mở tài khoản thanh toán số đẹp phong thủy online qua eKYC doanh nghiệp',
    category: 'Tài khoản doanh nghiệp',
    summary: 'Giải pháp mở tài khoản số đẹp theo yêu cầu trực tuyến 100% với công nghệ định danh eKYC đại diện pháp luật của VietinBank.',
    audience: 'SME & Hộ kinh doanh',
    websiteUrl: 'https://www.vietinbank.vn/web/home/vn/product/corporate/mo-tai-khoan-ekyc.html',
    facebookUrl: 'https://www.facebook.com/VietinBank/posts/98172635191',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.95,
    collectedAt: '2026-01-16T15:30:00Z',
    isDemo: false,
  },

  // 4. BIDV
  {
    id: 'intel-bidv-1',
    bankId: 'bank-bidv',
    bankName: 'BIDV',
    publishedAt: '2026-02-28',
    title: 'Hệ sinh thái BIDV Direct tích hợp quản trị dòng tiền & nộp thuế điện tử',
    category: 'Quản lý dòng tiền',
    summary: 'BIDV Direct kết nối API kế toán ERP doanh nghiệp, tự động đối soát sao kê tài khoản và nộp thuế điện tử thông quan 24/7.',
    audience: 'Corporate & Doanh nghiệp FDI',
    websiteUrl: 'https://www.bidv.com.vn/vi/khach-hang-doanh-nghiep/dich-vu-nop-thue-dien-tu',
    facebookUrl: 'https://www.facebook.com/BIDVbankvietnam/posts/871625341',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.96,
    collectedAt: '2026-03-01T09:40:00Z',
    isDemo: false,
  },
  {
    id: 'intel-bidv-2',
    bankId: 'bank-bidv',
    bankName: 'BIDV',
    publishedAt: '2026-01-10',
    title: 'Gói tín dụng xanh tài trợ vốn lưu động lãi suất ưu đãi cho SME',
    category: 'Tín dụng và khoản vay',
    summary: 'Chương trình tín dụng quy mô 10.000 tỷ đồng hỗ trợ doanh nghiệp chuyển đổi xanh và phát triển bền vững với lãi suất giảm tới 1.5%/năm.',
    audience: 'SME phát triển bền vững',
    websiteUrl: 'https://www.bidv.com.vn/vi/khach-hang-doanh-nghiep/tin-dung-xanh-sme',
    facebookUrl: 'https://www.facebook.com/BIDVbankvietnam/posts/871625342',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.94,
    collectedAt: '2026-01-11T13:00:00Z',
    isDemo: false,
  },

  // 5. VPBank
  {
    id: 'intel-vpb-1',
    bankId: 'bank-vpb',
    bankName: 'VPBank',
    publishedAt: '2026-03-02',
    title: 'VPBank NEOBiz ra mắt chi lương tự động 24/7 và thấu chi tín chấp 5 tỷ',
    category: 'Ngân hàng số doanh nghiệp',
    summary: 'Nền tảng NEOBiz cập nhật module chi lương theo lô liên ngân hàng tức thì và hạn mức thấu chi vốn lưu động phê duyệt trước 5 tỷ.',
    audience: 'SME & Hộ kinh doanh',
    websiteUrl: 'https://www.vpbank.com.vn/doanh-nghiep/chi-luong-online',
    facebookUrl: 'https://www.facebook.com/VPBankOfficial/posts/761524341',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.97,
    collectedAt: '2026-03-03T08:00:00Z',
    isDemo: false,
  },
  {
    id: 'intel-vpb-2',
    bankId: 'bank-vpb',
    bankName: 'VPBank',
    publishedAt: '2026-01-18',
    title: 'Miễn 100% phí chuyển tiền quốc tế trực tuyến trên VPBank NEOBiz',
    category: 'Chuyển tiền quốc tế',
    summary: 'Chính sách miễn toàn bộ phí chuyển tiền ngoại tệ ra nước ngoài trực tuyến cho khách hàng doanh nghiệp SME xuất nhập khẩu.',
    audience: 'Doanh nghiệp xuất nhập khẩu',
    websiteUrl: 'https://www.vpbank.com.vn/doanh-nghiep/chuyen-tien-quoc-te-online',
    facebookUrl: 'https://www.facebook.com/VPBankOfficial/posts/761524342',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.95,
    collectedAt: '2026-01-19T10:15:00Z',
    isDemo: false,
  },

  // 6. Vietcombank
  {
    id: 'intel-vcb-1',
    bankId: 'bank-vcb',
    bankName: 'Vietcombank',
    publishedAt: '2026-02-20',
    title: 'VCB DigiBiz triển khai dịch vụ Thu hộ qua mã tài khoản ảo (Virtual Account)',
    category: 'Thu hộ/chi hộ',
    summary: 'Hệ thống định danh giao dịch thu tiền bán hàng thông minh tự động gạch nợ cho các sàn thương mại điện tử và chuỗi phân phối.',
    audience: 'Doanh nghiệp TMĐT & Chuỗi phân phối',
    websiteUrl: 'https://www.vietcombank.com.vn/khach-hang-doanh-nghiep/dich-vu-thu-ho-va-chi-ho',
    facebookUrl: 'https://www.facebook.com/vietcombank/posts/6514231',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.98,
    collectedAt: '2026-02-21T09:00:00Z',
    isDemo: false,
  },
  {
    id: 'intel-vcb-2',
    bankId: 'bank-vcb',
    bankName: 'Vietcombank',
    publishedAt: '2026-01-22',
    title: 'Thẻ tín dụng doanh nghiệp Vietcombank Visa Corporate quản lý hạn mức phòng ban',
    category: 'Thẻ doanh nghiệp',
    summary: 'Công cụ quản trị chi phí công tác và mua sắm doanh nghiệp với tính năng phân bổ hạn mức chi tiêu cho từng nhân sự và bộ phận.',
    audience: 'Doanh nghiệp vừa và lớn',
    websiteUrl: 'https://www.vietcombank.com.vn/khach-hang-doanh-nghiep/the-doanh-nghiep-visa-corporate',
    facebookUrl: 'https://www.facebook.com/vietcombank/posts/6514232',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.96,
    collectedAt: '2026-01-23T11:20:00Z',
    isDemo: false,
  },

  // 7. ACB
  {
    id: 'intel-acb-1',
    bankId: 'bank-acb',
    bankName: 'ACB',
    publishedAt: '2026-02-14',
    title: 'ACB ONE BIZ bổ sung thanh toán hóa đơn theo lô và đối soát mã QR động',
    category: 'POS/QR',
    summary: 'Giải pháp thu tiền không dùng tiền mặt tích hợp quản lý doanh thu theo thời gian thực cho các cửa hàng bán lẻ và chuỗi cung ứng.',
    audience: 'Chuỗi bán lẻ & SME',
    websiteUrl: 'https://www.acb.com.vn/san-pham-dich-vu/khach-hang-doanh-nghiep/acb-one-biz-qr',
    facebookUrl: 'https://www.facebook.com/NganHangACB/posts/541321',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.95,
    collectedAt: '2026-02-15T16:00:00Z',
    isDemo: false,
  },

  // 8. Sacombank
  {
    id: 'intel-stb-1',
    bankId: 'bank-stb',
    bankName: 'Sacombank',
    publishedAt: '2026-02-05',
    title: 'Sacombank eBanking nâng cấp giải pháp Tài trợ chuỗi cung ứng (Supply Chain Finance)',
    category: 'Tài trợ thương mại',
    summary: 'Giải ngân trực tuyến cho nhà phân phối dựa trên chứng từ hóa đơn điện tử được xác nhận bởi doanh nghiệp đầu chuỗi.',
    audience: 'Nhà phân phối & Doanh nghiệp chuỗi',
    websiteUrl: 'https://www.sacombank.com.vn/doanh-nghiep/tai-tro-chuoi-cung-ung.html',
    facebookUrl: 'https://www.facebook.com/SacombankOfficial/posts/43121',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.94,
    collectedAt: '2026-02-06T10:45:00Z',
    isDemo: false,
  },

  // 9. SHB
  {
    id: 'intel-shb-1',
    bankId: 'bank-shb',
    bankName: 'SHB',
    publishedAt: '2026-01-30',
    title: 'SHB Corporate ra mắt gói giải pháp tín dụng cho nữ chủ doanh nghiệp SME',
    category: 'Tín dụng và khoản vay',
    summary: 'Gói vốn vay tín chấp ưu đãi lãi suất, miễn phí dịch vụ tài khoản và cung cấp gói đào tạo tài chính dành riêng cho doanh nghiệp do phụ nữ làm chủ.',
    audience: 'SME do phụ nữ làm chủ',
    websiteUrl: 'https://www.shb.com.vn/khach-hang-doanh-nghiep/goi-vay-nu-chu-sme',
    facebookUrl: 'https://www.facebook.com/SHBOfficial/posts/321',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.93,
    collectedAt: '2026-01-31T14:10:00Z',
    isDemo: false,
  },

  // 10. TPBank
  {
    id: 'intel-tpb-1',
    bankId: 'bank-tpb',
    bankName: 'TPBank',
    publishedAt: '2026-02-12',
    title: 'TPBank Biz triển khai sinh lời tự động trên số dư tài khoản thanh toán SME',
    category: 'Quản lý dòng tiền',
    summary: 'Tối ưu hóa dòng tiền nhàn rỗi trong ngày của doanh nghiệp với cơ chế tự động chuyển sang tài khoản tiền gửi sinh lời qua đêm.',
    audience: 'SME',
    websiteUrl: 'https://tpb.vn/khach-hang-doanh-nghiep/tai-khoan-sinh-loi-tu-dong',
    facebookUrl: 'https://www.facebook.com/TPBank/posts/211',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.97,
    collectedAt: '2026-02-13T09:30:00Z',
    isDemo: false,
  },

  // 11. HDBank
  {
    id: 'intel-hdb-1',
    bankId: 'bank-hdb',
    bankName: 'HDBank',
    publishedAt: '2026-01-28',
    title: 'HDBank e-Banking bổ sung phát hành L/C online nhanh 1h cho nông nghiệp',
    category: 'LC và bảo lãnh',
    summary: 'Quy trình thẩm định và cấp L/C tự động hóa phục vụ các doanh nghiệp xuất nhập khẩu lúa gạo, cà phê và nông thủy sản.',
    audience: 'Doanh nghiệp nông sản & Xuất khẩu',
    websiteUrl: 'https://hdbank.com.vn/vi/corporate/lc-online-nong-nghiep',
    facebookUrl: 'https://www.facebook.com/HDBankFanpage/posts/199',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.95,
    collectedAt: '2026-01-29T10:00:00Z',
    isDemo: false,
  },

  // 12. VIB
  {
    id: 'intel-vib-1',
    bankId: 'bank-vib',
    bankName: 'VIB',
    publishedAt: '2026-02-15',
    title: 'VIB mở cổng kết nối API ngân hàng mở (Open Banking) cho ERP doanh nghiệp',
    category: 'Tính năng mới',
    summary: 'Cho phép doanh nghiệp kết nối trực tiếp phần mềm quản trị kế toán nội bộ với ngân hàng để truy vấn số dư và duyệt chi tức thời.',
    audience: 'Doanh nghiệp công nghệ & FinTech',
    websiteUrl: 'https://vib.com.vn/vn/doanh-nghiep/open-banking-api',
    facebookUrl: 'https://www.facebook.com/VIB.NganHangQuocTe/posts/188',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.96,
    collectedAt: '2026-02-16T11:40:00Z',
    isDemo: false,
  },

  // 13. MSB
  {
    id: 'intel-msb-1',
    bankId: 'bank-msb',
    bankName: 'MSB',
    publishedAt: '2026-02-18',
    title: 'MSB M-Smart ra mắt hạn mức thấu chi doanh nghiệp duyệt tự động từ dữ liệu thuế',
    category: 'Tín dụng và khoản vay',
    summary: 'Doanh nghiệp chỉ cần chia sẻ tờ khai thuế điện tử để được cấp ngay hạn mức thấu chi tín chấp không cần tài sản bảo đảm trong 24h.',
    audience: 'SME & Hộ kinh doanh',
    websiteUrl: 'https://www.msb.com.vn/vi/doanh-nghiep/tin-dung-tin-chap-m-smart',
    facebookUrl: 'https://www.facebook.com/MSB.NganHangHangHai/posts/177',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.95,
    collectedAt: '2026-02-19T13:20:00Z',
    isDemo: false,
  },

  // 14. OCB
  {
    id: 'intel-ocb-1',
    bankId: 'bank-ocb',
    bankName: 'OCB',
    publishedAt: '2026-01-25',
    title: 'OCB OMNI Corp bổ sung phương thức xác thực Smart OTP phân quyền đa cấp',
    category: 'Ngân hàng số doanh nghiệp',
    summary: 'Cung cấp cơ chế phân quyền duyệt lệnh giao dịch linh hoạt nhiều tầng cho ban lãnh đạo và kế toán trưởng doanh nghiệp.',
    audience: 'Corporate & SME',
    websiteUrl: 'https://ocb.com.vn/vi/doanh-nghiep/smart-otp-omni-corp',
    facebookUrl: 'https://www.facebook.com/phuongdongbank/posts/166',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.94,
    collectedAt: '2026-01-26T15:00:00Z',
    isDemo: false,
  },

  // 15. SeABank
  {
    id: 'intel-ssb-1',
    bankId: 'bank-ssb',
    bankName: 'SeABank',
    publishedAt: '2026-02-08',
    title: 'SeABank ra mắt gói tài trợ trọn gói cho doanh nghiệp năng lượng tái tạo',
    category: 'Tài trợ thương mại',
    summary: 'Gói giải pháp tài chính bao gồm vốn vay dài hạn, bảo lãnh thực hiện hợp đồng và thanh toán quốc tế cho các dự án điện mặt trời mái nhà.',
    audience: 'Doanh nghiệp năng lượng',
    websiteUrl: 'https://www.seabank.com.vn/doanh-nghiep/tin-dung-xanh',
    facebookUrl: 'https://www.facebook.com/NganhangSeABank/posts/155',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.93,
    collectedAt: '2026-02-09T08:45:00Z',
    isDemo: false,
  },

  // 16. Agribank
  {
    id: 'intel-agr-1',
    bankId: 'bank-agr',
    bankName: 'Agribank',
    publishedAt: '2026-01-20',
    title: 'Agribank triển khai chuyển tiền quốc tế trực tuyến đa ngoại tệ trên E-Banking Doanh nghiệp',
    category: 'Chuyển tiền quốc tế',
    summary: 'Doanh nghiệp khu vực nông nghiệp nông thôn thực hiện điện chuyển tiền SWIFT trực tiếp trên kênh số không cần tới quầy giao dịch.',
    audience: 'Doanh nghiệp xuất nhập khẩu nông sản',
    websiteUrl: 'https://www.agribank.com.vn/vn/khach-hang-doanh-nghiep/chuyen-tien-quoc-te',
    facebookUrl: 'https://www.facebook.com/agribankvietnam/posts/144',
    sourceTypes: ['website', 'facebook'],
    verificationStatus: 'verified',
    confidenceScore: 0.92,
    collectedAt: '2026-01-21T09:10:00Z',
    isDemo: false,
  },

  // Items for "Cần rà soát" (Review status - e.g. missing post permalink or date)
  {
    id: 'intel-review-1',
    bankId: 'bank-vcb',
    bankName: 'Vietcombank',
    publishedAt: '', // Date missing -> triggers review status
    title: 'Vietcombank cập nhật điều khoản dịch vụ tài khoản doanh nghiệp trực tuyến',
    category: 'Tài khoản doanh nghiệp',
    summary: 'Thông báo sửa đổi quy định giao dịch ngân hàng số, không xác định được ngày đăng bài chính xác.',
    audience: 'Khách hàng tổ chức',
    websiteUrl: 'https://www.vietcombank.com.vn/khach-hang-doanh-nghiep',
    sourceTypes: ['website'],
    verificationStatus: 'review',
    confidenceScore: 0.60,
    collectedAt: '2026-02-10T11:00:00Z',
    isDemo: false,
  },
  {
    id: 'intel-review-2',
    bankId: 'bank-shb',
    bankName: 'SHB',
    publishedAt: '2026-02-02',
    title: 'Chương trình tri ân đối tác doanh nghiệp đồng hành cùng SHB',
    category: 'Ưu đãi/khuyến mại mới',
    summary: 'Bài viết Facebook có đề cập gói ưu đãi nhưng permalink cụ thể bị giới hạn truy cập từ nền tảng Meta.',
    audience: 'SME',
    facebookUrl: 'https://www.facebook.com/SHBOfficial',
    sourceTypes: ['facebook'],
    verificationStatus: 'review',
    confidenceScore: 0.55,
    collectedAt: '2026-02-03T14:30:00Z',
    isDemo: false,
  },
];

export const INITIAL_SOURCE_ALERTS: SourceAlert[] = [
  {
    id: 'alert-1',
    bankId: 'bank-vcb',
    bankName: 'Vietcombank',
    sourceType: 'facebook',
    errorCause: 'Yêu cầu đăng nhập tài khoản Facebook để lấy permalink bài viết cụ thể',
    checkedAt: '2026-03-02T10:15:00Z',
    resolved: false,
  },
  {
    id: 'alert-2',
    bankId: 'bank-agr',
    bankName: 'Agribank',
    sourceType: 'website',
    errorCause: 'Máy chủ phản hồi chậm (>20s timeout khi quét trang con)',
    httpStatus: 504,
    checkedAt: '2026-03-01T14:20:00Z',
    resolved: false,
  },
  {
    id: 'alert-3',
    bankId: 'bank-shb',
    bankName: 'SHB',
    sourceType: 'facebook',
    errorCause: 'Vượt hạn mức truy vấn API công khai (Meta Rate Limit)',
    httpStatus: 429,
    checkedAt: '2026-02-28T09:00:00Z',
    resolved: false,
  },
];

